# Generated by Django 6.0.4 on 2026-04-25 15:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pages.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('asn', models.PositiveBigIntegerField(unique=True, validators=[pages.validators.validate_private_asn], verbose_name='AS number')),
                ('ipv4_peering_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4 peering address')),
                ('ipv6_peering_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IPv6 peering address')),
                ('max_prefix_v4', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum IPv4 prefixes')),
                ('max_prefix_v6', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum IPv6 prefixes')),
                ('peeringdb_url', models.URLField(blank=True, null=True, verbose_name='PeeringDB URL')),
                ('connect_rs1', models.BooleanField(default=True, verbose_name='connect to route server 1')),
                ('connect_rs2', models.BooleanField(default=False, verbose_name='connect to route server 2')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_participant_registrations', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participant registration',
                'verbose_name_plural': 'participant registrations',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BGPSessionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_server', models.CharField(choices=[('RS1', 'Route Server 1'), ('RS2', 'Route Server 2')], max_length=3)),
                ('session_state', models.CharField(choices=[('Idle', 'Idle'), ('Connect', 'Connect'), ('Active', 'Active'), ('OpenSent', 'OpenSent'), ('OpenConfirm', 'OpenConfirm'), ('Established', 'Established')], default='Idle', max_length=20)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('prefixes_received', models.PositiveIntegerField(default=0)),
                ('prefixes_advertised', models.PositiveIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_session_statuses', to='pages.participantregistration')),
            ],
            options={
                'verbose_name': 'BGP session status',
                'verbose_name_plural': 'BGP session statuses',
                'ordering': ['participant', 'route_server'],
            },
        ),
        migrations.CreateModel(
            name='PrefixRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=43, validators=[pages.validators.validate_ip_prefix])),
                ('ip_version', models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefix_registrations', to='pages.participantregistration')),
            ],
            options={
                'verbose_name': 'prefix registration',
                'verbose_name_plural': 'prefix registrations',
                'ordering': ['participant', 'ip_version', 'prefix'],
            },
        ),
        migrations.CreateModel(
            name='VPNAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_ipv4', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='VPN IPv4 address')),
                ('vpn_ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', unique=True, verbose_name='VPN IPv6 address')),
                ('wireguard_public_key', models.CharField(blank=True, max_length=88, null=True, validators=[pages.validators.validate_wireguard_public_key])),
                ('config_generated', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_assignment', to='pages.participantregistration')),
            ],
            options={
                'verbose_name': 'VPN assignment',
                'verbose_name_plural': 'VPN assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='participantregistration',
            index=models.Index(fields=['organisation_name'], name='participant_org_idx'),
        ),
        migrations.AddIndex(
            model_name='participantregistration',
            index=models.Index(fields=['status'], name='participant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='participantregistration',
            index=models.Index(fields=['status', 'submitted_at'], name='participant_status_sub_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantregistration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asn__gte', 64512), ('asn__lte', 65534)), models.Q(('asn__gte', 4200000000), ('asn__lte', 4294967294)), _connector='OR'), name='participant_private_asn_range'),
        ),
        migrations.AddConstraint(
            model_name='participantregistration',
            constraint=models.CheckConstraint(condition=models.Q(('max_prefix_v4__gte', 1)), name='participant_max_pfx4_positive'),
        ),
        migrations.AddConstraint(
            model_name='participantregistration',
            constraint=models.CheckConstraint(condition=models.Q(('max_prefix_v6__gte', 1)), name='participant_max_pfx6_positive'),
        ),
        migrations.AddIndex(
            model_name='bgpsessionstatus',
            index=models.Index(fields=['route_server', 'session_state'], name='bgp_route_server_state_idx'),
        ),
        migrations.AddIndex(
            model_name='bgpsessionstatus',
            index=models.Index(fields=['participant', 'last_seen'], name='bgp_participant_last_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='bgpsessionstatus',
            constraint=models.UniqueConstraint(fields=('participant', 'route_server'), name='unique_participant_rs'),
        ),
        migrations.AddIndex(
            model_name='prefixregistration',
            index=models.Index(fields=['participant', 'ip_version'], name='prefix_participant_version_idx'),
        ),
        migrations.AddIndex(
            model_name='prefixregistration',
            index=models.Index(fields=['is_active'], name='prefix_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='prefixregistration',
            constraint=models.UniqueConstraint(fields=('participant', 'prefix'), name='unique_participant_prefix'),
        ),
        migrations.AddIndex(
            model_name='vpnassignment',
            index=models.Index(fields=['config_generated'], name='vpn_config_generated_idx'),
        ),
    ]
