# Generated by Django 6.0.4 on 2026-05-03 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeeringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('none', 'No Session')], default='none', max_length=10)),
                ('established_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'peering session',
                'verbose_name_plural': 'peering sessions',
                'ordering': ['member_a__asn', 'member_b__asn'],
            },
        ),
        migrations.CreateModel(
            name='PrefixFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50, verbose_name='prefix or rule description')),
                ('action', models.CharField(choices=[('permit', 'Permit'), ('deny', 'Deny')], max_length=10)),
                ('family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], max_length=4)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='max prefix length (optional)')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = evaluated first')),
            ],
            options={
                'verbose_name': 'prefix filter',
                'verbose_name_plural': 'prefix filters',
                'ordering': ['family', 'direction', 'order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bgpsessionstatus',
            name='unique_participant_rs',
        ),
        migrations.AddField(
            model_name='bgpsessionstatus',
            name='family',
            field=models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], default='ipv4', max_length=4, verbose_name='IP family'),
        ),
        migrations.AddField(
            model_name='bgpsessionstatus',
            name='uptime_seconds',
            field=models.PositiveBigIntegerField(default=0, verbose_name='uptime in seconds'),
        ),
        migrations.AddConstraint(
            model_name='bgpsessionstatus',
            constraint=models.UniqueConstraint(fields=('participant', 'route_server', 'family'), name='unique_participant_rs_family'),
        ),
        migrations.AddField(
            model_name='peeringsession',
            name='member_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peering_as_a', to='pages.participantregistration'),
        ),
        migrations.AddField(
            model_name='peeringsession',
            name='member_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peering_as_b', to='pages.participantregistration'),
        ),
        migrations.AddField(
            model_name='prefixfilter',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefix_filters', to='pages.participantregistration', verbose_name='participant (null = global)'),
        ),
        migrations.AddIndex(
            model_name='peeringsession',
            index=models.Index(fields=['status'], name='peering_status_idx'),
        ),
        migrations.AddIndex(
            model_name='peeringsession',
            index=models.Index(fields=['member_a', 'status'], name='peering_a_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='peeringsession',
            constraint=models.UniqueConstraint(fields=('member_a', 'member_b'), name='unique_peering_session'),
        ),
        migrations.AddConstraint(
            model_name='peeringsession',
            constraint=models.CheckConstraint(condition=models.Q(('member_a', models.F('member_b')), _negated=True), name='peering_no_self_session'),
        ),
        migrations.AddIndex(
            model_name='prefixfilter',
            index=models.Index(fields=['family', 'direction'], name='filter_family_direction_idx'),
        ),
        migrations.AddIndex(
            model_name='prefixfilter',
            index=models.Index(fields=['participant'], name='filter_participant_idx'),
        ),
    ]
